resources:
  - ../../../../eei-k8s/base-dev/postgres

components:
  - ../../common/namespace
  - ../../common/pvc

secretGenerator:
  - name: db-siu
    envs:
      - ../../secrets/postgres-secrets.env
    behavior: merge
