apiVersion: batch/v1
kind: Job
metadata:
  name: proveedores-crear-base
spec:
  ttlSecondsAfterFinished: 3600
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      imagePullSecrets:
        - name: hub.siu.edu.ar
      volumes:
        - name: secrets
          secret:
            secretName: proveedores
            defaultMode: 0600
      initContainers:
        - name: verificar-conexion
          image: postgres:13
          envFrom:
            - configMapRef:
                name: proveedores.env
          volumeMounts:
            - name: secrets
              mountPath: /var/secrets
          command: ["/bin/bash", "-c"]
          args:
            - |
              export PGPASSWORD=$(cat ${ARAI_PROVEEDORES_DB_PASSWORD_FILE})
              until pg_isready -h ${ARAI_PROVEEDORES_DB_HOST} -U ${ARAI_PROVEEDORES_DB_USERNAME} > /dev/null 2>&1
              do
                echo "Esperando a que ${ARAI_PROVEEDORES_DB_HOST} acepte conexiones"
                sleep 5
              done
              echo "${ARAI_PROVEEDORES_DB_HOST} está listo"
        - name: crear-base-datos
          image: postgres:13
          envFrom:
            - configMapRef:
                name: proveedores.env
          volumeMounts:
            - name: secrets
              mountPath: /var/secrets
          command: ["/bin/bash", "-c"]
          args:
            - |
              export PGPASSWORD=$(cat ${ARAI_PROVEEDORES_DB_PASSWORD_FILE})
              psql -h ${ARAI_PROVEEDORES_DB_HOST} -U ${ARAI_PROVEEDORES_DB_USERNAME} -d postgres -c "CREATE DATABASE ${ARAI_PROVEEDORES_DB_DBNAME};"
              echo "Base de datos ${ARAI_PROVEEDORES_DB_DBNAME} creada"
      containers:
      - name: crear-estructura-base
        image: hub.siu.edu.ar:5005/siu/expedientes/proveedores-api:v2.0.3
        envFrom:
          - configMapRef:
              name: proveedores.env
        volumeMounts:
          - name: secrets
            mountPath: /var/secrets
        command: ["/entrypoint.sh", "--reconfigure", "--db-initialize"]