kind: Component

secretGenerator:
  - name: docs-stamper
    envs:
      - ../../../secrets/docs-stamper-secrets.env
  - name: docs-stamper-keystore
    files:
      - ../../../secrets/keystore_stamper.p12