resources:
  - ../../../../siu-k8s/base-eei/1.9.0/arai/solicitudes/jobs/update

components:
  - ../../../apps/solicitudes/config
  - ../../../apps/solicitudes/secrets
  - ../../../common
  - ../../../apps/solicitudes/namespace