apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sudocu-files
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sudocu-tmp
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi