apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-siu
spec:
  selector:
    matchLabels:
      app: db-siu
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: db-siu
    spec:
      volumes:
        - name: secret
          secret:
            secretName: db-siu
        - name: config
          configMap:
            name: db-siu
        - name: data
          persistentVolumeClaim:
            claimName: db-siu-data
        - name: dshm
          emptyDir:
            medium: Memory
      containers:
        - name: postgres
          image: postgres:13-bookworm
          imagePullPolicy: Always
          env:
            - name: TZ
              value: "America/Buenos_Aires"
            - name: LANG
              value: "es_AR.UTF-8"
            - name: POSTGRES_PASSWORD_FILE
              value: /usr/local/POSTGRES_PASSWORD
          volumeMounts:
            - name: secret
              mountPath: /usr/local/POSTGRES_PASSWORD
              subPath: POSTGRES_PASSWORD
            - name: config
              mountPath: /etc/postgresql
            - name: data
              mountPath: /var/lib/postgresql/data
            - name: dshm
              mountPath: /dev/shm
          command: ["/bin/bash", "-c"]
          args:
            - |
              # Fix para volumes con formato ext4 que al crear el directorio lost+found hace que falle el initdb
              rm -d /var/lib/postgresql/data/lost+found
              chmod -R 777 /dev/shm
              localedef -i es_AR -c -f UTF-8 -A /usr/share/locale/locale.alias es_AR.UTF-8
              docker-entrypoint.sh postgres -c 'config_file=/etc/postgresql/postgresql.conf'
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: db-siu
spec:
  selector:
    app: db-siu
  ports:
    - port: 5432
      targetPort: 5432
