apiVersion: apps/v1
kind: Deployment
metadata:
  name: usuarios-api
spec:
  selector:
    matchLabels:
      app: usuarios-api
  template:
    metadata:
      labels:
        app: usuarios-api
    spec:
      imagePullSecrets:
        - name: hub.siu.edu.ar
      volumes:
        - name: secrets
          secret:
            secretName: usuarios
        - name: resources-data
          persistentVolumeClaim:
            claimName: usuarios-resources-data
      containers:
        - name: usuarios-api
          image: hub.siu.edu.ar:5005/siu/expedientes/arai-usuarios/api:v3.3.0
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: usuarios.env
            - configMapRef:
                name: usuarios-api.env
          volumeMounts:
            - name: secrets
              mountPath: /var/secrets
            - name: resources-data
              mountPath: /usr/local/app/resources
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
---
apiVersion: v1
kind: Service
metadata:
  name: usuarios-api
spec:
  selector:
    app: usuarios-api
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: usuarios-api
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /api/$1
spec:
  ingressClassName: nginx
  rules:
    - host: uunn.local
      http:
        paths:
          - path: /api-usuarios/(.+)
            pathType: ImplementationSpecific
            backend:
              service:
                name: usuarios-api
                port:
                  number: 80
  tls:
    - hosts:
        - uunn.local
      secretName: uunn.local
