resources:
  - ../../../siu-k8s/base-eei/1.9.0/sudocu

patches:
  - path: patches/pvc-storage-patch-files.yaml
    target:
      kind: PersistentVolumeClaim
      name: sudocu-files
  - path: patches/pvc-storage-patch-tmp.yaml
    target:
      kind: PersistentVolumeClaim
      name: sudocu-tmp

components:
  - config
  - secrets
  - ../../secrets
  - ../../common
  - namespace