apiVersion: apps/v1
kind: Deployment
metadata:
  name: docs-stamper
spec:
  selector:
    matchLabels:
      app: docs-stamper
  template:
    metadata:
      labels:
        app: docs-stamper
    spec:
      volumes:
        - name: config
          configMap:
            name: docs-stamper
        - name: keystore-stamper
          secret:
            secretName: docs-stamper-keystore
      containers:
        - name: docs-stamper
          image: ungs/sudocu-estampador:1.0.0
          envFrom:
            - configMapRef:
                name: docs-stamper.env
            - secretRef:
                name: docs-stamper
          volumeMounts:
            - name: keystore-stamper
              mountPath: /app/classes/config/keystore_stamper.p12
              subPath: keystore_stamper.p12
            - name: config
              mountPath: /app/classes/config/application.properties
              subPath: application.properties
            - name: config
              mountPath: /app/docs_stamper_entrypoint.sh
              subPath: docs_stamper_entrypoint.sh
            - name: config
              mountPath: /app/classes/config/firma.png
              subPath: firma.png
          command: ["/bin/sh", "-x"]
          args: ["/app/docs_stamper_entrypoint.sh"]
          # args:
          #   - |
          #     while true; do sleep 100; done
          resources:
            requests:
              cpu: 50m
              memory: 300Mi
---
apiVersion: v1
kind: Service
metadata:
  name: docs-stamper
spec:
  selector:
    app: docs-stamper
  ports:
    - port: 8080
      targetPort: 8080