apiVersion: apps/v1
kind: Deployment
metadata:
  name: personas-api
spec:
  selector:
    matchLabels:
      app: personas-api
  template:
    metadata:
      labels:
        app: personas-api
    spec:
      imagePullSecrets:
        - name: hub.siu.edu.ar
      volumes:
        - name: secrets
          secret:
            secretName: personas
      containers:
        - name: personas-api
          image: hub.siu.edu.ar:5005/siu/expedientes/arai-personas/api:v1.0.1
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: personas.env
            - configMapRef:
                name: personas-api.env
          volumeMounts:
            - name: secrets
              mountPath: /var/secrets
          resources:
            requests:
              cpu: 50m
              memory: 50Mi
---
apiVersion: v1
kind: Service
metadata:
  name: personas-api
spec:
  selector:
    app: personas-api
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: personas-api
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /api/$1
spec:
  ingressClassName: nginx
  rules:
    - host: uunn.local
      http:
        paths:
          - path: /api-personas/(.+)
            pathType: ImplementationSpecific
            backend:
              service:
                name: personas-api
                port:
                  number: 8080
  tls:
    - hosts:
        - uunn.local
      secretName: uunn.local
