apiVersion: apps/v1
kind: Deployment
metadata:
  name: sudocu-gestion
spec:
  selector:
    matchLabels:
      app: sudocu-gestion
  template:
    metadata:
      labels:
        app: sudocu-gestion
    spec:
      volumes:
        - name: config
          configMap:
            name: sudocu-config
      containers:
        - name: sudocu-gestion
          image: ungs/sudocu-gestion:1.4.17
          env:
            - name: TZ
              value: "America/Buenos_Aires"
          volumeMounts:
            - name: config
              mountPath: /app/config.json
              subPath: config-sudocu-gestion.json
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
---
apiVersion: v1
kind: Service
metadata:
  name: sudocu-gestion
spec:
  selector:
    app: sudocu-gestion
  ports:
    - port: 3020
      targetPort: 3020
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sudocu-gestion
  annotations:
    nginx.ingress.kubernetes.io/configuration-snippet: |
     rewrite ^(/sudocu/gestion)$ $1/ redirect;
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: uunn.local
      http:
        paths:
          - path: /sudocu/gestion(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: sudocu-gestion
                port:
                  number: 3020
  tls:
    - hosts:
        - uunn.local
      secretName: uunn.local