kind: Component

resources: []

secretGenerator:
  - name: sudocu-config
    files:
      - sudocu-api-server=sudocu-api-server-secret.json
    behavior: merge
  - name: sudocu
    envs:
      - sudocu-secrets.env
    behavior: merge