apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
spec:
  selector:
    matchLabels:
      app: minio
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: minio
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: minio-data
      containers:
        - name: minio
          # https://github.com/minio/minio/releases
          # https://hub.docker.com/r/minio/minio/tags
          image: minio/minio:RELEASE.2024-07-26T20-48-21Z-cpuv1
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: minio
          volumeMounts:
            - name: data 
              mountPath: /data
          command: ["/bin/bash", "-c"]
          args:
            - |
              mkdir -p /data/documentos
              mkdir -p /data/sudocu-files
              minio server /data --console-address ":9001"
          resources:
            requests:
              cpu: 50m
              memory: 200Mi
---
apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  selector:
    app: minio
  ports:
    - port: 9000
      targetPort: 9000
      name: api
    - port: 9001
      targetPort: 9001
      name: console